name: KWEK Deployment File

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [prod]
  #pull_request:
   # branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: ${{ secrets.KWEK_HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       source /home/kwekxbyu/virtualenv/kwek/3.8/bin/activate && cd /home/kwekxbyu/kwek
      #       git pull origin prod
      #       pip install -r requirements.txt
      #       python manage.py makeigrations
      #       python manage.py migrate
      #       python manage.py collectstatic
      #       yes
      #       python passenger_wsgi.py 

      - name: Exec remote commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: premium219.web-hosting.com
          # port: 2083
          # port: ${{ secrets.PORT }}
          # password: ${{ secrets.PASSWORD }}
          # username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: uZOKTPXdDXKo
          username: kwekxbyu
          script: |
            source /home/kwekxbyu/virtualenv/kwek/3.8/bin/activate && cd /home/kwekxbyu/kwek
            git pull upstream prod
            pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py makemigrations bill kwek kwek_auth market notifications users walle
            python manage.py migrate
            python manage.py collectstatic --noinput
            python passenger_wsgi.py 